name: Release

on:
  release:
    types: [ created ]

jobs:
  upload-assets:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: image-inverter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
